# Generated by Django 4.2 on 2024-09-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Free', '자유 게시판'), ('Ask', '질문 게시판'), ('Company', '홍보 게시판')], max_length=7),
        ),
    ]
