# Generated by Django 4.2 on 2024-09-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_authenticated',
            new_name='is_mine',
        ),
    ]
