# Generated by Django 4.2 on 2024-09-13 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nbcns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbcn',
            name='bookmark_nbcns',
        ),
        migrations.AddField(
            model_name='nbcn',
            name='nbcn_bookmark_users',
            field=models.ManyToManyField(related_name='bookmark_nbcns', to=settings.AUTH_USER_MODEL),
        ),
    ]
